# Generated by Django 5.2.5 on 2025-08-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome usuário')),
                ('email', models.CharField(max_length=255, verbose_name='Email usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Sobre as tarefas')),
                ('nomeSala', models.CharField(max_length=255, verbose_name='Nome da sua sala')),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Media'), ('A', 'Alta')], default='B', max_length=5, verbose_name='Prioridade da tarefa')),
                ('status', models.CharField(choices=[('AF', 'A fazer'), ('F', 'Fazendo'), ('P', 'Pronto')], default='AF', max_length=7, verbose_name='Status da tarefa')),
                ('dataCadastro', models.DateField(verbose_name='Data inicial da tarefa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='app.usuario')),
            ],
        ),
    ]
